$("#ShowDropdownTable").click(function(){
    $(".TableResults").each(function(){
        $(".TableResults").show(250);
    });
});
$("#HideDropdownTable").click(function(){
    $(".TableResults").each(function(){
        $(".TableResults").hide(250);
    });
});